### ISSUE TITLE
Implement `any`

### ISSUE THREAD

**Issue by StephanMeijer** [noahbuscher/Macaw#34]
I think it would be useful to be able to match a route, but to ignore the HTTP Request Method. Can you implement such a feature?

**Comment by daveismyname** [comment]
What I've done is use 'any' that way it matches both post and get replace line 77 with this:

````
if (self::$methods[$route] == $method || self::$methods[$route] == 'ANY') {
````

then you can do any any:

````
Macaw::any('/', function() {
  echo 'Hello world!';
});
````

**Comment by noahbuscher** [comment]
Merged PR! Match away!

Thanks, @daveismyname. :clap:
