### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by huangzhwork** [noahbuscher/Macaw#37]
```
Warning: preg_match(): Compilation failed: unmatched parentheses at offset 15 in D:\Work\www\routine\vendor\noahbuscher\macaw\Macaw.php on line 117
```
How to fix it?

**Comment by badaozhai** [comment]
I have this problem too,The err info is like this:
Warning: preg_match(): Compilation failed: unmatched parentheses at offset 5 in E:\myCode\mymvc\vendor\noahbuscher\macaw\Macaw.php on line 120

**Comment by badaozhai** [comment]
I use Macaw like this:
Macaw::get('/', function() {
    echo 'Hello world!';
});

Macaw::get('index', function() {
    echo "sucess！";
});

Macaw::get('(:all)', function($fu) {
    echo '404'.$fu;
});

Macaw::dispatch();

when i annotate the code:
Macaw::get('(:all)', function($fu) {
    echo '404'.$fu;
});
it works ok;

**Comment by badaozhai** [comment]
Now,I have found the reason ,it`s my x-debug notice info，If I closed the notice,I sloved the problem;
