### ISSUE TITLE
Install in subdir

### ISSUE THREAD

**Issue by FakePlasticBees** [noahbuscher/Macaw#47]
I have made a small site and want to use it as a virtual site in a subdirectory. Not sure if that is a good so i'll try to explain. I have one placeholdersite/server with a couple of subdirs. With a .htacces file on the root each domain is redirected to the subdir.

```
/placeholder.com
 .htaccess
 /domain1
  - index.php
 /domain2
  - index.php
 /domain3
  - index.php
```

When I upload my site to this subdir and visit the site I only get a 404. On the local server everything work fine.  I guess there is an issue with the path and I tried several things but most end in a server error. 

Is there a way to get this working?

**Comment by daveismyname** [comment]
this may not be an issue anymore but I would have a separate .htaccess file in each subfolder in each case adjusting the rewrite base.
