### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by cnbailian** [noahbuscher/Macaw#48]
Macaw::get('bug', function(){
    echo "string";
});

127.0.0.1/bug
true
127.0.0.1/asass/bug
false
127.0.0.1/index.php/bug
true

but
127.0.0.1/index.php/asass/bug
true

**Comment by ricardovfreixo** [comment]
This was a long time now. have you figured out? 

Also, I couldn't actually replicate the error. can you give a more compreensive example? and include your htaccess please

**Comment by cnbailian** [comment]
@ricardovfreixo 
Because has passed for too long, all I did was test again, using the current code
Found the problem still exists, the study found that the problem occurs in Macaw.php: 29

```
dirname($_SERVER ['PHP_SELF']) 
```
changed to 
```
$_SERVER['PHP_SELF']
```

My environment is php7.0 + Apache / 2.4.18
