### ISSUE TITLE
Controller to handle URL not found instead of 404 message

### ISSUE THREAD

**Issue by novhex** [noahbuscher/Macaw#51]
How do i route the user to my error controller instead of showing plain text ?

my controller for 404 is located at app/controllers/error404.php
`
<?php

class Error404 extends Controller{

	public function index(){
		
		$this->show('error/404');
	}
}`
what should i put in Macaw::error?

Thanks :)

**Comment by bhoggett** [comment]
Same as any normal routing callback.

e.g. if your error controller is called `ErrorController` and the method for showing the 404 error was `notFound()` then you'd use:

`Macaw::error('MyApp\Controllers\ErrorController@notFound');`

If you MUST pass a parameter to your error method then your _notFound()_ method could be like this:

`notFound() {
    this->show('error/404');
}`

**Comment by ArtyumX** [comment]
Strange... it didn't work for me, it keeps showing "404".
Here is my route : 
`Router::error('Controllers\ErrorController@index');`

And my class : 
```
class ErrorController
{

    public function index() {
        if (empty($_SESSION['username']) {
            View::render('404-userNotLogged', ['page_title' => 'Erreur 404']);
        } else {
            View::render('404', ['page_title' => 'Erreur 404']);
        }
    }

}
```
