### ISSUE TITLE
unmatched routing

### ISSUE THREAD

**Issue by stonenyy** [noahbuscher/Macaw#57]
behind modify the route and controller, show me  unmatched routing in new version.

--------
routes.php:
use \NoahBuscher\Macaw\Macaw;
Macaw::get('/', 'Controller\Home@home');
Macaw::dispatch();

--------
home.php:(controller)
namespace Controller;
class Home extends BaseController
{
public function home() {}
}

**Comment by noahbuscher** [comment]
Rolled back lastest merge - insufficient testing. Thanks for pointing this out!
