### ISSUE TITLE
Code improve

### ISSUE THREAD

**Issue by biaoqianwo** [noahbuscher/Macaw#59]
I think `$uri = dirname($_SERVER['PHP_SELF']).'/'.$params[0];` in  line 29  
should improve to 
`$uri = strpos($params[0], '/') === 0 ? $params[0] : dirname($_SERVER['PHP_SELF']) . '/' . $params[0];`

or else

`Macaw::get('/users/(:num)', 'Bee\Controllers\Users@show');`
is not ok for `http://127.0.0.1:8000/users/1`
The server is opened by `php -S 127.0.0.1:8000`

**Comment by noahbuscher** [comment]
Merged PR! Thank you for pointing that out.
