### ISSUE TITLE
Route that handles multiple HTTP methods

### ISSUE THREAD

**Issue by ArtyumX** [noahbuscher/macaw#67]
It would be cool to have something like this : 

```php
Macaw::map(['GET', 'POST'], '/page', function () {
    echo 'Hello world!';
});
```

Thanks.

**Comment by daveismyname** [comment]
You can use `any` that will respond to both get and post requests. 

```php
Macaw::any('page', function () {
    echo 'Hello world!';
});
```

**Comment by ArtyumX** [comment]
I'm aware about this method, thanks.
But it will respond to all HTTP methods, not **only** to GET and POST method in my instance.

**Comment by daveismyname** [comment]
I've just submitted a PR that adds this function https://github.com/noahbuscher/Macaw/pull/69

for now you can access my alterations at https://github.com/daveismyname/Macaw/blob/patch-2/Macaw.php

**Comment by ArtyumX** [comment]
Thank you!
