### ISSUE TITLE
Hi, I've some problem for routing

### ISSUE THREAD

**Issue by mcyumustutan** [noahbuscher/macaw#73]
My Folder is
-Controller
 ---Demo.php
-vendor
-.htaccess
-index.php

My localhost url: http://localhost/test/macaw/

/------My .htaccess file-----
RewriteEngine On
RewriteBase /test/macaw/
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?$1 [QSA,L]

-------/

My index.php file and my demo.php file like yours readme file (https://github.com/noahbuscher/Macaw/#example-passing-to-a-controller-instead-of-a-closure)

But I see 404 on my page. 
Can you see where i make mistakes?
Thank you.

**Comment by daveismyname** [comment]
I don't only that I don't see a composer.json file in your example.

**Comment by mcyumustutan** [comment]
Thanks for your interest. 
my composer.json file
{
	"require": {
		"noahbuscher/macaw": "dev-master",
		"smarty/smarty": "~3.1",
		"php-curl-class/php-curl-class": "^7.3",
	},
	"autoload": {
		"files": [
		],
		"psr-4": {
			"": ""
		}
	}
}

**Comment by GHBJayce** [comment]
I think I solved this problem, Do not know if my approach is correct, Only two lines of code.

Changed place
`Macaw.php`

line 25
```diff
  public static $error_callback;
+ public static $root;
```

line 63
```diff

  public static function dispatch(){
    $uri = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
+   !empty(self::$root) && self::$root !== '/' && $uri = self::$root === $uri ? '/' : substr_replace($uri, '', strpos($uri, self::$root), strlen(self::$root));
    $method = $_SERVER['REQUEST_METHOD'];
    ...
  }
```

route
```php
<?php

use NoahBuscher\Macaw\Macaw;

Macaw::$root = 'test/macaw';

Macaw::get('test', function () {
  echo 'ok';
});

Macaw::dispatch();

```

access url: http://localhost/test/macaw/test

**Comment by ppazos** [comment]
I did something similar for adding a base URL to route but changed the code in a different way https://github.com/ppazos/amplify-prototype/blame/master/router/Macaw.php
