### ISSUE TITLE
Error when using same route with different methods

### ISSUE THREAD

**Issue by SteveHawes** [noahbuscher/macaw#74]
My route.php file contains:

`Macaw::post('/api/pages/partials', 'EWS\API\Pages@getPartials');
Macaw::get('/api/pages/partial/(:num)', 'EWS\API\Pages@getPartial');`

If I make a call to the API using /api/pages/partial/3 using the method GET everything works fine - so far so good.

If I now update the route file to contain:

`Macaw::post('/api/pages/partials', 'EWS\API\Pages@getPartials');
Macaw::get('/api/pages/partial/(:num)', 'EWS\API\Pages@getPartial');
Macaw::put('/api/pages/partial/(:num)', 'EWS\API\Pages@updatePartial');`

and again make the call to /api/pages/partial/3 using the method GET I get the error:

`"Warning: in_array() expects parameter 2 to be array, null given in vendor/noahbuscher/macaw/Macaw.php on line 117"`

Debugging the PHP shows that the call is matched as expected (and the getPartial routine is run) but it then continues to try and match the routes and when it gets to the put version the self::maps[$pos] is null so the error is thrown.

How can I have two identical routes but for different methods without this error occurring?

Thanks

**Comment by SteveHawes** [comment]
Looks like this is related to the new maps option that was merged recently. Unless I am missing something it looks like there is now no way to add a route that for the same target that has different endpoints for each method (GET, POST, PUT etc.). 

I will happily stand corrected if someone can show me how :)

**Comment by daveismyname** [comment]
you're correct I've just tested this, if you use the map option you can then use the same endpoint for different methods:

```
Macaw::post('api/pages/partials', 'EWS\API\Pages@getPartials');
Macaw::map(['get'], 'api/pages/partial/(:num)', 'EWS\API\Pages@getPartial');
Macaw::map(['put'], 'api/pages/partial/(:num)', 'EWS\API\Pages@updatePartial');
```

**Comment by SteveHawes** [comment]
Thanks for the swift reply and the workaround.

Can I suggest the following change which would allow the original syntax to work but have no impact on the integrity of the map functionality?

Change line 117 of Macaw.php to:
            if (self::$methods[$pos] == $method || self::$methods[$pos] == 'ANY' || (!empty(self::$maps[$pos]) && in_array($method, self::$maps[$pos]))) {

This would avoid anyone else running into the same issue going forward.

Thanks
Steve
