### ISSUE TITLE
Warning: in_array() expects parameter 2 to be array, null given on line 78

### ISSUE THREAD

**Issue by idlana** [noahbuscher/macaw#77]
![tt](https://user-images.githubusercontent.com/18338607/36213157-d8d6fe7e-115a-11e8-86ad-45eeb78b6959.png)

`Macaw::get('test', function() {
  echo 'Hello world!';
});`

**Comment by ShelterYa** [comment]
may be you request with post. however, this is a warning, but a exception.

**Comment by ShelterYa** [comment]
you can use Route::any to resolve it temporarily.

**Comment by ppazos** [comment]
Getting the same issue. Problem is defining a route as post only and using GET on that route. IMO that should return Method Not Allowed, since some URLs should be POST only.

**Comment by daveismyname** [comment]
until the PR's are merged you can manually update the Macaw file: https://github.com/noahbuscher/macaw/pull/79/files
