### ISSUE TITLE
Redirect

### ISSUE THREAD

**Issue by jimgwhit** [noahbuscher/Macaw#90]
I have tried several different ways to redirect with no success.

For example after a login
```
Url::redirect('dog/indexadmin');
```

And that method:
```
    public static function redirect($url = null, $fullpath = false, $code = 200)
    {
        $url = ($fullpath === false) ? DIR . $url : $url;  // tried commenting out
        if ($code == 200) {
            header('Location: ' . $url);
        } else {
            header('Location: ' . $url, true, $code);
        }
        exit;
    }
```

DIR  is just /mini4/.  Tried without it.  Also have tried many combinations:
```
Url::redirect('dog/indexadmin');
Url::redirect('/dog/indexadmin');
Url::redirect('http://localhost/mini4/dog/indexadmin');
Url::redirect('/mini4/dog/indexadmin');
Url::redirect('mini4/dog/indexadmin');
```

I just cannot seem to do a redirect.

If I, after logging in type the url in the address bar, it works, so routing is working, but no redirects.

The redirect method is from SMVC framework, from David Carr.  But I even tried direct redirects using:
```
$url = 'dog/indexadmin';
header('Location: '.$url);  // tried all the above in the variable.
die;
```

Please help.

**Comment by kazuyamarino** [comment]
I use macaw too.

I have create method for redirect like this in my own framework.
```
function redirect($url = null, $code = 200)
{
  header("Location:". base_url($url), true, $code);
  exit();
}
```
And for `base_url()` method, the output is `http://localhost/nsy`, where `nsy` is my project dir inside htdocs or www dir.

then, when I write `base_url('dog/indexadmin')`, it's map to `http://localhost/nsy/dog/indexadmin`

hope this help.

**Comment by dcblogdev** [comment]
hi @jimgwhit I'm not stalking you I swear lol

I've just tried this on a new sample project and redirects are working for me too:

composer.json
```
{
    "require": {
        "noahbuscher/macaw": "dev-master",
        "filp/whoops": "^2.7"
    },
    "autoload": {
        "psr-4": {
            "App\\" : "App/"
        }
    }
}
```

/public/index.php

```php
<?php
require('../vendor/autoload.php');

$whoops = new \Whoops\Run;
$whoops->pushHandler(new \Whoops\Handler\PrettyPageHandler);
$whoops->register();

use NoahBuscher\Macaw\Macaw as Route;

define('DIR', 'http://demo.localhost/');

Route::get('/', 'App\Controllers\Demo@index');
Route::get('page', 'App\Controllers\demo@page');
Route::get('view/(:num)', 'App\Controllers\demo@view');

Route::dispatch();
```

App/Controllers/Demo.php
```php
<?php

namespace App\Controllers;

class Demo {

    public function index()
    {
        self::redirect('view/3');
    }

    public function page()
    {
        echo 'page';
    }

    public function view($id)
    {
        echo $id;
    }

    public static function redirect($url = null, $fullpath = false, $code = 200)
    {
        $url = ($fullpath === false) ? DIR . $url : $url;  // tried commenting out
        if ($code == 200) {
            header('Location: ' . $url);
        } else {
            header('Location: ' . $url, true, $code);
        }
        exit;
    }

}
```

**Comment by jimgwhit** [comment]
Thank both of you for the code samples.  I will try the code.

**Comment by jimgwhit** [comment]
Was the above code taking into account the new $root PR?

https://github.com/noahbuscher/macaw/pull/78/commits/5e5cde7838da4c1dab3cfb15da37f1d53dfa82ba

Instead of
```
Macaw::get('dog/indexadmin', '\\Mini\\Controller\\DogController@indexAdmin');
```

I now have to:
```
Macaw::get('mini4/dog/indexadmin', '\\Mini\\Controller\\DogController@indexAdmin');
```

I don't quite get what that $root PR is doing. But I will keep trying.  Note this is just test data I use.

Is this router supposed to only be used in the root folder?  I will try later with a new project.

**Comment by dcblogdev** [comment]
> Was the above code taking into account the new $root PR?

no it wasn't but that does make sense since the route is based on the url requested ie: `$_SERVER['REQUEST_URI']`

I don't ever make sub directory projects I always create a full domain or sub domain that way Its easy to keep sensitive files above the document root.

**Comment by dcblogdev** [comment]
> I don't quite get what that $root PR is doing. But I will keep trying. Note this is just test data I use.

Looks like you set the project root and then your routes don't have to change.

**Comment by jimgwhit** [comment]
Main project is above htdocs, I install with composer, and have:
Have new mini5 project
In index
```
//  code
define('ROOTUP', realpath(__DIR__ . '/../../mini5up') . DIRECTORY_SEPARATOR);
require ROOTUP . 'application/Core/Routes.php';
```

Routes file:
```
<?php

use NoahBuscher\Macaw\Macaw as Route;

Route::get('mini5/admin/login', '\\Mini\\Controller\\AdminController@login');
Route::get('mini5/dog/indexadmin', '\\Mini\\Controller\\DogController@indexAdmin');
Route::get('mini5/dog/index', '\\Mini\\Controller\\DogController@index');

Route::dispatch();
```

These routes work, but still no redirect, I tried:
```
Url::redirect('http://localhost/mini5/dog/index');
// whole url
```

And changed retirect method to:
```
    public static function redirect($url)
    {
        header('Location: ' . $url);
        exit;
    }

```

Even with the whole url, still no redirect, just 404 is displayed.  Is it because main code is above htdocs.

Note however, after login, I can paste:
```
http://localhost/mini5/dog/index    // for rexample
```
In address bar and it works, so the router is working, just no redirect.  What am I doing wrong?

**Comment by kazuyamarino** [comment]
Hi, 
If your project dir is above root/htdocs dir.

The route file must be like this 
```
<?php

use NoahBuscher\Macaw\Macaw as Route;

Route::get('/admin/login', '\\Mini\\Controller\\AdminController@login');
Route::get('/dog/indexadmin', '\\Mini\\Controller\\DogController@indexAdmin');
Route::get('/dog/index', '\\Mini\\Controller\\DogController@index');

Route::dispatch();
```

why did i remove mini5 from routing?
because I assume the mini5 file & dir is in public/root/htdocs

**Comment by kazuyamarino** [comment]
i have an example of the project [Here](https://github.com/kazuyamarino/route-test)

and in web with apache [Here](https://staging.polimerz.com/)

**Comment by jimgwhit** [comment]
Thanks @kazuyamarino  and  @daveismyname I will further test.

Funny thing @daveismyname  I have an old SMVC project I test, with main files above htdocs.

I replaced the smvc router with macaw, it worked, but still had to put the leading uri.

Had to put
```
Macaw router
Router::any('crudm/admin/login', '\Controllers\Admin@logIn');
```

But the router in smvc I had just:
```
SMVC router
Router::any('admin/login', 'Controllers\Admin@logIn');
```

I'm closing, but please add any additional tips.

I temporarily went back to the router without the new $root, working for now still having to add the extra leading site name.

That extra site name is not needed in the old SMVC router.  I will continue to experiment.
